Repository Catch-Python-Study/algorithm-study, pull requests merged in 2021-06, with the labels that each got.

#25 4주차 제출
  eojin/3주차/조이스틱.py
  eojin/4주차/모의고사.py
  eojin/4주차/크레인 인형뽑기 게임.py
  eojin/4주차/키패드 누르기.py
Labels: All solved ❤️, solved 👍

#23 4주차 과제 완료 및 21.05.28 self-study 추가
  kwangjin/4주차/claw_crane_game.py
  kwangjin/4주차/keypad.py
  kwangjin/4주차/practice_test.py
  kwangjin/input.txt
  kwangjin/self-study/2021.05.28/[2798]blackjack.py
  kwangjin/self-study/2021.05.28/[2869]snail.py
  kwangjin/self-study/2021.05.28/[4153]right_triangle.py
  kwangjin/self-study/2021.05.28/[4949]balanced_world.py
  kwangjin/self-study/2021.05.28/[7568]bulk.py
  kwangjin/self-study/2021.05.30/[9012]bracket.py
  kwangjin/self-study/2021.05.30/selling_toothbrush.py
  kwangjin/self-study/2021.05.31/[10250]ACM_hotel.py
  kwangjin/self-study/2021.05.31/[10773]zero.py
  kwangjin/self-study/2021.05.31/[10814]sort_age.py
  kwangjin/self-study/2021.05.31/[10816]num_card_2.py
  kwangjin/self-study/2021.05.31/[10828]stack.py
  kwangjin/self-study/2021.05.31/[10845]queue.py
  kwangjin/self-study/2021.05.31/[10866]deque.py
  kwangjin/self-study/2021.05.31/[10989]sort_num_3.py
  kwangjin/self-study/2021.06.01/[11050]binomial_coefficient.py
  kwangjin/self-study/2021.06.01/[11650]coordinate_alignment.py
  kwangjin/self-study/2021.06.01/[11651]cordinate_alignment_2.py
  kwangjin/self-study/2021.06.01/[11866]Josephus.py
  kwangjin/self-study/2021.06.01/[15829]Hashing.py
Labels: All solved ❤️, solved 👍

#24 4주차 과제 all solved
  jangwon/.DS_Store
  jangwon/4주차/4-1/모의고사.js
  jangwon/4주차/4-1/모의고사.py
  jangwon/4주차/4-1/크레인인형뽑기게임.js
  jangwon/4주차/4-1/크레인인형뽑기게임.py
  jangwon/4주차/4-1/키패드누르기.js
  jangwon/4주차/4-1/키패드누르기.py
Labels: All solved ❤️, solved 👍

#29 4주차 2 기능개발
  jangwon/4주차/4-2/기능개발.py
  jangwon/Solo/boj/9012.md
  ouput.txt
Labels: solved 👍, 아직 다 풀지 못했어요

#32 4주차 목요일
  eojin/4주차/기능 개발.py
  eojin/4주차/더 맵게.py
Labels: All solved ❤️

#34 5weeks ing
  .vscode/launch.json
  .vscode/settings.json
  README.md
  jangwon/4주차/4-2/더맵게.py
  jangwon/5주차/5-1/단어변환.js
  jangwon/5주차/5-1/단어변환.py
Labels: Programmers, question

#38 feat:[5주차]word_trans.py solved!
  kwangjin/5주차/lotto.py
  kwangjin/5주차/open_chat.py
  kwangjin/5주차/word_trans.py
  kwangjin/input.txt
  kwangjin/self-study/2021.06.03/[1003]fibonacci.py
  kwangjin/self-study/2021.06.07/[1012]organic_cabbage.py
  kwangjin/self-study/2021.06.08/ad_insert.py
Labels: All solved ❤️

#37 5주차 제출
  jangwon/5주차/5-1/로또의최고순위와최저순위.py
  jangwon/5주차/5-1/오픈채팅방.py
  jangwon/5주차/5-2/음양더하기.py
  jangwon/5주차/5-2/회사에있는사람.py
Labels: All solved ❤️, Programmers, solved 👍, 구현, 다이나믹프로그래밍

#40 [5주차]목요일 과제 완료 및 문제 해결 요청
  kwangjin/5주차/[7785]in_company.py
  kwangjin/5주차/plus.py
  kwangjin/6주차/[17826]my_score.py
  kwangjin/6주차/[17836]princess.py
  kwangjin/6주차/[17845]subject.py
  kwangjin/input.txt
  kwangjin/self-study/2021.06.08/ad_insert.py
  kwangjin/self-study/2021.06.10/[1074]Z.py
  kwangjin/self-study/2021.06.14/[1107]remote.py
  kwangjin/self-study/2021.06.14/[1260]DFS and BFS.py
Labels: All solved ❤️, DP, help wanted, 구현

#42 Self: 5weeks prog heap 디스크 컨트롤러 solved
  jangwon/5주차/self/디스크컨트롤러.py
  jangwon/Self/알고리즘구현/서로소집합/cycle_find.py
  jangwon/Self/알고리즘구현/서로소집합/union_find.py
  jangwon/Self/알고리즘구현/최단거리알고리즘(다익스트라)/dijkstart2.py
  jangwon/Self/알고리즘구현/최단거리알고리즘(다익스트라)/dijkstra1.py
  jangwon/Self/알고리즘구현/최단거리알고리즘(다익스트라)/jeonbo.py
Labels: Heap 🐶, Programmers, 구현

#36 최인선_7785_회사에 있는 사람_백준
  insun/incompany.py
  insun/lotto.py
Labels: BOJ, solved 👍

#44 [6주차] 제출
  eojin/6주차/공주님을 구하라.py
  eojin/6주차/나의 학점은.py
  eojin/6주차/수강 과목.py
  eojin/6주차/유기농배추.py
  eojin/6주차/팬케익 뒤집기.py
Labels: All solved ❤️, BOJ, DFS BFS, DP, 구현

#46 6주차 제출
  input.txt
  jangwon/6주차/6-1/나의학점은.py
  jangwon/6주차/6-1/수강과목.py
  jangwon/6주차/6-2/유기농배추.py
  jangwon/7주차/boj11404.py
  jangwon/7주차/boj1389.py
  jangwon/7주차/sixshop.py
  jangwon/7주차/나무자르기.py
  jangwon/7주차/쿼드압축후개수세기.js
  jangwon/7주차/쿼드압축후개수세기.py
  jangwon/Self/알고리즘구현/다익스트라 문제/배달.js
  jangwon/Self/알고리즘구현/다익스트라 문제/배달.py
Labels: BOJ, solved 👍, 구현

#47 7주차 제출
  eojin/7주차/괄호 변환.py
  eojin/7주차/뉴스클러스팅.py
  eojin/7주차/멀쩡한사각형.py
  eojin/7주차/방금그곡.py
  eojin/7주차/쿼드압축후개수세기.py
Labels: All solved ❤️, 구현, 완전 탐색, 재귀, 해시

#49 7주차 화요일 과제 완료!
  kwangjin/6주차/[1012]Organic_Cabbage.py
  kwangjin/6주차/[17836]princess.py
  kwangjin/7주차/news_clustering.py
  kwangjin/7주차/quad_comp_and_cnt.py
  kwangjin/7주차/square.py
  kwangjin/7주차/the_song.py
  kwangjin/8주차/carpet.py
  kwangjin/8주차/num_124.py
  kwangjin/8주차/other_solve.py
  kwangjin/8주차/sort_filename.py
  kwangjin/8주차/tuple.py
  kwangjin/input.txt
  kwangjin/self-study/2021.06.14/[1260]DFS and BFS.py
  kwangjin/self-study/2021.06.21/[1389]6step.py
  kwangjin/self-study/2021.06.23/[1676]factorial_0_cnt.py
  kwangjin/self-study/2021.06.23/[1780]cnt_paper.py
  kwangjin/self-study/2021.06.23/[1992]quad_tree.py
  kwangjin/self-study/2021.06.23/[2178]maze_escape.py
  kwangjin/self-study/2021.06.24/Unique Paths.py
  kwangjin/self-study/2021.06.25/new_id_reco.py
  kwangjin/self-study/2021.06.27/be_one.py
  kwangjin/self-study/2021.06.29/[1620]pocketmon_master.py
  kwangjin/self-study/2021.06.29/[1697]hide and seek.py
Labels: All solved ❤️, Programmers, 구현, 재귀
