Repository Catch-Python-Study/algorithm-study, pull requests merged in 2021-08, with the labels that each got.

#69 12주차 이광진
  kwangjin/12주차/num_game.py
  kwangjin/12주차/setup.py
  kwangjin/13주차/fight.py
  kwangjin/13주차/ground.py
  kwangjin/self-study/2021.07/2021.07.01/backpack.py
  kwangjin/self-study/2021.07/2021.07.01/change_coin.py
  kwangjin/self-study/2021.07/2021.07.01/max_score.py
  kwangjin/self-study/2021.07/2021.07.01/min_dis_graph.py
  kwangjin/self-study/2021.07/2021.07.02/lan_cut.py
  kwangjin/self-study/2021.07/2021.07.02/postfix.py
  kwangjin/self-study/2021.07/2021.07.02/president.py
  kwangjin/self-study/2021.07/2021.07.11/[2579] Climbing_stairs.py
  kwangjin/self-study/2021.07/2021.07.11/[2606]virus.py
Labels: Greedy, Programmers, solved 👍, 아직 다 풀지 못했어요

#76 [14주차] 윤장원
  jangwon/12주차/입국심사.js
  jangwon/13주차/땅따먹기.py
  jangwon/14주차/뉴스클러스터링.py
  jangwon/14주차/숫자문자열과영단어.py
Labels: All solved ❤️, Programmers, 구현

#74 14주차 문제 2문제 완료!
  kwangjin/14주차/news_clustering.py
  kwangjin/14주차/num&str_list.py
Labels: 구현
